### ISSUE TITLE
java.lang.SecurityException: Permission Denial: opening provider 

### ISSUE THREAD

**Issue by 2math** [diegoveloper/flutter_keyboard_actions#109]
Since Flutter 1.20 I have this issue in the logs on all screens that has KeyboardActions. The app is working but this error is in the logs for each KeyboardActionItem.

I was using 3.2.1+1 , after  ubdate to 3.3.0+1 the problem remains

Device is Pixel 3a XL

W/ClipData(22469): Failure opening stream
W/ClipData(22469): java.lang.SecurityException: Permission Denial: opening provider org.chromium.chrome.browser.util.ChromeFileProvider from ProcessRecord{33fd4d0 22469:appId/u0a463} (pid=22469, uid=10463) that is not exported from UID 10133
W/ClipData(22469): 	at android.os.Parcel.createException(Parcel.java:2071)
W/ClipData(22469): 	at android.os.Parcel.readException(Parcel.java:2039)
W/ClipData(22469): 	at android.os.Parcel.readException(Parcel.java:1987)
W/ClipData(22469): 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5056)
W/ClipData(22469): 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6561)
W/ClipData(22469): 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2725)
W/ClipData(22469): 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2117)
W/ClipData(22469): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1671)
W/ClipData(22469): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1625)
W/ClipData(22469): 	at android.content.ClipData$Item.coerceToText(ClipData.java:364)
W/ClipData(22469): 	at io.flutter.plugin.platform.PlatformPlugin.getClipboardData(PlatformPlugin.java:278)
W/ClipData(22469): 	at io.flutter.plugin.platform.PlatformPlugin.access$700(PlatformPlugin.java:24)
W/ClipData(22469): 	at io.flutter.plugin.platform.PlatformPlugin$1.getClipboardData(PlatformPlugin.java:81)
W/ClipData(22469): 	at io.flutter.embedding.engine.systemchannels.PlatformChannel$1.onMethodCall(PlatformChannel.java:141)
W/ClipData(22469): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
W/ClipData(22469): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/ClipData(22469): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
W/ClipData(22469): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/ClipData(22469): 	at android.os.MessageQueue.next(MessageQueue.java:336)
W/ClipData(22469): 	at android.os.Looper.loop(Looper.java:174)
W/ClipData(22469): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
W/ClipData(22469): 	at java.lang.reflect.Method.invoke(Native Method)
W/ClipData(22469): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/ClipData(22469): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by 2math** [comment]
This is related to new TextField somehow :(
