### ISSUE TITLE
Errors in ReorderableListView with autoscroll == true

### ISSUE THREAD

**Issue by shalom-aviv** [diegoveloper/flutter_keyboard_actions#149]
Sorry can not provide sample now

```
======== Exception caught by rendering library =====================================================
The following _CastError was thrown during paint():
Null check operator used on a null value

The relevant error-causing widget was: 
  ReorderableListView-[<'__todoList__'>] fmain_deals_list.dart:36:49
When the exception was thrown, this was the stack: 
#0      RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:653:25)
#1      RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:645:7)
#2      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2319:7)
#3      PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:139:11)
#4      PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
...
The following RenderObject was being processed when the exception was fired: RenderViewport#2832b
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=358.0, 0.0<=h<=696.0)
...  layer: OffsetLayer#f9a9c
...    engine layer: OffsetEngineLayer#b947b
...    offset: Offset(56.0, 166.0)
...  size: Size(358.0, 696.0)
...  axisDirection: down
...  crossAxisDirection: right
...  offset: ScrollPositionWithSingleContext#67611(offset: 0.0, range: null..null, viewport: 696.0, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#aa0bf, ScrollDirection.idle)
...  anchor: 0.0
RenderObject: RenderViewport#2832b
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=358.0, 0.0<=h<=696.0)
  layer: OffsetLayer#f9a9c
    engine layer: OffsetEngineLayer#b947b
    offset: Offset(56.0, 166.0)
  size: Size(358.0, 696.0)
  axisDirection: down
  crossAxisDirection: right
  offset: ScrollPositionWithSingleContext#67611(offset: 0.0, range: null..null, viewport: 696.0, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#aa0bf, ScrollDirection.idle)
  anchor: 0.0
...  center child: RenderSliverPadding#3aa1e relayoutBoundary=up1 NEEDS-PAINT
...    needs compositing
...    parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 696.0, crossAxisExtent: 358.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 696.0, remainingCacheExtent: 946.0, cacheOrigin: 0.0)
...    geometry: null
...    padding: EdgeInsets.zero
...    textDirection: ltr
...    child: RenderSliverList#8060c relayoutBoundary=up2 NEEDS-PAINT
...      needs compositing
...      parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...      constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 696.0, crossAxisExtent: 358.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 696.0, remainingCacheExtent: 946.0, cacheOrigin: 0.0)
...      geometry: null
...      currently live children: 0 to 0
...      child with index 0: RenderIndexedSemantics#55834 relayoutBoundary=up3 NEEDS-PAINT
...        needs compositing
...        parentData: index=0; layoutOffset=0.0 (can use size)
...        constraints: BoxConstraints(w=358.0, 0.0<=h<=Infinity)
...        semantic boundary
...        size: MISSING
...        index: 0
...        child: RenderRepaintBoundary#3b34a relayoutBoundary=up4 NEEDS-PAINT
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=358.0, 0.0<=h<=Infinity)
...          size: MISSING
...          usefulness ratio: no metrics collected yet (never painted)
====================================================================================================
```

**Comment by diegoveloper** [comment]
Add a minimum sample code to reproduce the issue
