### ISSUE TITLE
Setting disableScroll: true throws null value error

### ISSUE THREAD

**Issue by a-shak** [diegoveloper/flutter_keyboard_actions#181]
Setting `disableScroll: true` ends up throwing a null error:
````
======== Exception caught by scheduler library =====================================================
The following _CastError was thrown during a scheduler callback:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      KeyboardActionstate._distanceBelowWidget (package:keyboard_actions/keyboard_actions.dart:158:34)
#1      KeyboardActionstate._updateOffset (package:keyboard_actions/keyboard_actions.dart:442:20)
#2      KeyboardActionstate.didChangeMetrics.<anonymous closure> (package:keyboard_actions/keyboard_actions.dart:314:7)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1088:9)
#5      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#9      _invoke (dart:ui/hooks.dart:166:10)
#10     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#11     _drawFrame (dart:ui/hooks.dart:129:31)
(elided 3 frames from dart:async)
====================================================================================================
````

I created a new flutter app, added keyboard_actions, then reproduced with the following in main.dart:
````
import 'package:flutter/material.dart';
import 'package:keyboard_actions/keyboard_actions.dart';
import 'package:keyboard_actions/keyboard_actions_config.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  final focusNode = FocusNode();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: ListView(
        physics: const ClampingScrollPhysics(),
        children: [
          KeyboardActions(
            config: _buildConfig(context),
            autoScroll: false,
            disableScroll: true,
            child: TextField(
              focusNode: focusNode,
              keyboardType: TextInputType.multiline,
              onChanged: (text) {

              },
              onTap: () {

              },
            ),
          ),
        ],
      ),// This trailing comma makes auto-formatting nicer for build methods.
    );
  }


  /// Custom Keyboard Close
  KeyboardActionsConfig _buildConfig(BuildContext context) {
    return KeyboardActionsConfig(
        keyboardActionsPlatform: KeyboardActionsPlatform.ALL,
        nextFocus: false,
        actions: [
          KeyboardActionsItem(
            focusNode: focusNode,
            toolbarButtons: [
                  (node) {
                return GestureDetector(
                  onTap: () => node.unfocus(),
                  child: Container(
                    margin: const EdgeInsets.only(right: 10),
                    child: const Padding(
                      padding: EdgeInsets.all(8.0),
                      child: Text(
                        'Done',
                      ),
                    ),
                  ),
                );
              }
            ],
          ),
        ]
    );
  }
}
````

Output of flutter doctor:
````
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.5.1 20G80 darwin-x64, locale en-US)
    • Flutter version 2.5.3 at /Users/adam/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/adam/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (4 available)
    • Adam’s iPhone (mobile)     • 00008020-000A4C9A1E29002E            • ios            • iOS 14.7.1 18G82
    • iPhone 11 Pro Max (mobile) • CC84D1A9-44C1-4FF3-8C27-B3B7FCB1802E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.5.1 20G80 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 98.0.4758.80

• No issues found!
````

Making the following change in line 439 of keyboard_actions.dart seems to fix it but it couldn't tell if it was a legitimate fix
`    if (!widget.isDialog && !widget.disableScroll) {`

**Comment by jhuckabee** [comment]
@a-shak I ran into the same issue you were having. Have you tried using the version on [`master`](0a1ab0912299e729361a83af65f82326a249ffea)? It has #180 merged, and it looks like that fixes the issue for me.

**Comment by acacioveit** [comment]
Master does fix the issue, but can you please generate a new release?

**Comment by naamapps** [comment]
Up!
Can you please deploy to pub.dev the new version?
Thanks
