### ISSUE TITLE
A FocusNode was used after being disposed.

### ISSUE THREAD

**Issue by stevenspiel** [diegoveloper/flutter_keyboard_actions#22]
I'm hitting an error with version `2.1.1` (upgrading from `1.0.3`):

<details>
<summary>logs</summary>

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown while finalizing the widget tree:
flutter: A FocusNode was used after being disposed.
flutter: Once you have called dispose() on a FocusNode, it can no longer be used.
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:105:9)
flutter: #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:111:6)
flutter: #2      ChangeNotifier.removeListener (package:flutter/src/foundation/change_notifier.dart:166:12)
flutter: #3      FormKeyboardActionState._dismissListeningFocus.<anonymous closure> (package:keyboard_actions/keyboard_actions.dart:261:38)
flutter: #4      Iterable.forEach (dart:core/iterable.dart:277:30)
flutter: #5      FormKeyboardActionState._dismissListeningFocus (package:keyboard_actions/keyboard_actions.dart:260:17)
flutter: #6      FormKeyboardActionState.clearConfig (package:keyboard_actions/keyboard_actions.dart:166:5)
flutter: #7      FormKeyboardActionState.dispose (package:keyboard_actions/keyboard_actions.dart:342:5)
flutter: #8      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:3916:12)
flutter: #9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1697:13)
flutter: #10     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #12     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #13     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #17     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4965:16)
flutter: #18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #20     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #29     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
flutter: #30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #35     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
flutter: #36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #40     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #41     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #42     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #43     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #44     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #45     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #46     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #47     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #48     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #49     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #50     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #51     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #52     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #53     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #54     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #55     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #56     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
flutter: #57     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #58     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #59     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #60     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #61     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #62     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
flutter: #63     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #64     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #65     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
flutter: #66     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #67     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #68     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4965:16)
flutter: #69     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #70     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #71     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #72     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #73     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #74     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
flutter: #75     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #76     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #77     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #78     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #79     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #80     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
flutter: #81     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #82     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #83     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #84     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #85     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #86     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
flutter: #87     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #88     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #89     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #90     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #91     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #92     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #93     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #94     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #95     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #96     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #97     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #98     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
flutter: #99     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #100    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #101    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #102    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #103    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #104    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
flutter: #105    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #106    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #107    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #108    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #109    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #110    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #111    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #112    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #113    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
flutter: #114    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #115    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #116    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #117    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #118    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #119    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #120    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #121    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #122    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #123    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #124    ListIterable.forEach (dart:_internal/iterable.dart:39:13)
flutter: #125    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1706:25)
flutter: #126    BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2364:27)
flutter: #127    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2196:15)
flutter: #128    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2363:7)
flutter: #129    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:702:18)
flutter: #130    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #131    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
flutter: #132    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
flutter: #133    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
flutter: #137    _invoke (dart:ui/hooks.dart:219:10)
flutter: #138    _drawFrame (dart:ui/hooks.dart:178:3)
flutter: (elided 3 frames from package dart:async)
```

</details>

My code follows the example pretty closely. I'm running into it when I navigate to a page with keyboard actions, pop navigation, and then again navigate to the keyboard actions route again. 

[This basic flutter app reproduces the issue (Github)](https://github.com/stevenspiel/flutter_keyboard_issue_22): 
- (just hit the (+) button, then the X in the top left to go back. The error is in the logs, but you see the page blow up when you try to hit the (+) button again).

The problem is that [line 259](https://github.com/diegoveloper/flutter_keyboard_actions/blob/ef4ab4a706288597fb0b339e4fcbddfed92995d7/lib/keyboard_actions.dart#L259) is trying to remove listeners from focus nodes that were previously disposed of.

The first page looks like this:

```dart
import 'package:flutter/material.dart';

import 'form_page.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('example'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Navigator.of(context).push(
            MaterialPageRoute(
              builder: (BuildContext context) => FormPage(isEditing: false),
            ),
          );
        },
        child: Icon(Icons.add),
      ),
    );
  }
}
```

and the form page is this:

```dart
import 'package:flutter/material.dart';
import 'package:keyboard_actions/keyboard_actions.dart';

class FormPage extends StatelessWidget {
  final bool isEditing;

  FormPage({
    Key key,
    @required this.isEditing,
  })  : super(key: key ?? Key(isEditing ? 'editing' : 'creating'));

  static final _scaffoldKey = GlobalKey<ScaffoldState>();
  static final GlobalKey<FormState> _formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: _scaffoldKey,
      appBar: AppBar(
        leading: IconButton(
          icon: Icon(Icons.clear),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(isEditing ? "Edit Herd Record" : "New Herd Record"),
      ),
      body: FormKeyboardActions(
        child: _FormContent(
          isEditing: isEditing,
          formKey: _formKey,
          scaffoldKey: _scaffoldKey,
        ),
      ),
    );
  }
}

class _FormContent extends StatefulWidget {
  final bool isEditing;
  final GlobalKey<ScaffoldState> scaffoldKey;
  final GlobalKey<FormState> formKey;

  _FormContent({
    Key key,
    @required this.isEditing,
    @required this.formKey,
    @required this.scaffoldKey,
  });

  @override _FormContentState createState() => _FormContentState(
    nameTextEditingController: TextEditingController(text: null),
  );
}

class _FormContentState extends State<_FormContent> {
  final FocusNode focusNodeName = FocusNode();

  final TextEditingController nameTextEditingController;

  _FormContentState({
    @required this.nameTextEditingController,
  });

  GlobalKey<FormState> get _formKey => widget.formKey;
  GlobalKey<ScaffoldState> get _scaffoldKey => widget.scaffoldKey;

  String _name;

  @override
  void initState() {
    _name = '';

    // Configure keyboard actions
    FormKeyboardActions.setKeyboardActions(context, _buildConfig(context));
    super.initState();
  }

  KeyboardActionsConfig _buildConfig(BuildContext context) {
    return KeyboardActionsConfig(
      keyboardActionsPlatform: KeyboardActionsPlatform.ALL,
      actions: [
        KeyboardAction(focusNode: focusNodeName),
      ]
    );
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.only(left: 16, right: 16),
      child: Form(
        key: _formKey,
        child: SingleChildScrollView(
          child: Column(mainAxisAlignment: MainAxisAlignment.start, crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              SafeArea(bottom: false,
                child: Align(alignment: Alignment.center,
                  child: Container(constraints: BoxConstraints(maxWidth: 600),
                    child: Column(
                      children: <Widget>[
                        const SizedBox(height: 16),
                        _nameField(), const SizedBox(height: 24),
                      ],
                    )
                  )
                ),
              )
            ],
          )
        ),
      ),
    );
  }

  Widget _nameField() {
    return TextFormField(
      focusNode: focusNodeName,
      initialValue: _name,
      decoration: const InputDecoration(labelText: 'Name'),
    );
  }

  @override
  void dispose() {
    focusNodeName.dispose();
    nameTextEditingController.dispose();

    super.dispose();
  }
}
```

should I not be calling `dispose` on the focusNode?

**Comment by diegoveloper** [comment]
Don't worry about disposing `focusNode`, these are already disposed when you close the widget.

**Comment by stevenspiel** [comment]
That did it. Thanks!
