### ISSUE TITLE
How to use with Column as a parent and multiline TextField

### ISSUE THREAD

**Issue by AndroidGecko** [diegoveloper/flutter_keyboard_actions#49]
Hey @diegoveloper 

I have tweaked your sample.dart to illustrate the issue.

I'm getting `BoxConstraints forces an infinite height`.
If you remove the `Column`, everything works as expected.
If I wrap `FormKeyboardActions` in  `Container` with the fixed height it also works.

My question is - is it possible to make it work without setting the fixed height?
Thanks!

```dart
import 'package:flutter/material.dart';
import 'package:keyboard_actions/keyboard_actions.dart';
//https://github.com/hackiftekhar/IQKeyboardManager

class Sample extends StatelessWidget {
  final _focusNodeQuantity = FocusNode();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("KeyboardActions"),
      ),
      body: Column(
        children: <Widget>[
          FormKeyboardActions(
            config: KeyboardActionsConfig(actions: [
              KeyboardAction(
                focusNode: _focusNodeQuantity,
              ),
            ]),
            child: TextField(
              focusNode: _focusNodeQuantity,
              keyboardType: TextInputType.multiline,
              maxLines: null,
            ),
          ),
        ],
      ),
    );
  }
}

```

**Comment by diegoveloper** [comment]
Add this property nextFocus false inside keyboardActionConfig

**Comment by AndroidGecko** [comment]
Thanks for your quick response!
Added `nextFocus: false`. Still getting the issue unfortunately

```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
BoxConstraints forces an infinite height.

These invalid constraints were provided to RenderSemanticsAnnotations's layout() function by the following function, which probably computed the invalid constraints in question:
  RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
The offending constraints were: BoxConstraints(w=392.7, h=Infinity)
User-created ancestor of the error-causing widget was: 
  FormKeyboardActions file:///Users/marcin/coding/git/flutter/flutter_keyboard_actions/example/lib/sample.dart:16:11
When the exception was thrown, this was the stack: 
#0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:501:9)
#1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:548:21)
#2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:552:6)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1618:24)
#4      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
...
The following RenderObject was being processed when the exception was fired: RenderConstrainedBox#a3daa relayoutBoundary=up17 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=392.7, 0.0<=h<=Infinity)
...  size: MISSING
...  additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=Infinity)
RenderObject: RenderConstrainedBox#a3daa relayoutBoundary=up17 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=392.7, 0.0<=h<=Infinity)
  size: MISSING
  additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=Infinity)
...  child: RenderSemanticsAnnotations#668ad NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: <none>
...    constraints: MISSING
...    size: MISSING
...    child: RenderMouseRegion#2a2f5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none>
...      constraints: MISSING
...      size: MISSING
...      listeners: enter, exit
...      child: RenderIgnorePointer#53c92 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none>
...        constraints: MISSING
...        size: MISSING
...        ignoring: false
...        ignoringSemantics: implicitly false
...        child: RenderPointerListener#38244 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none>
...          constraints: MISSING
...          size: MISSING
...          behavior: translucent
...          listeners: down
```

**Comment by diegoveloper** [comment]
That was for this question "up/down interface on the left"

**Comment by AndroidGecko** [comment]
>That was for this question "up/down interface on the left"
ah, sorry
I've left this question by mistake and edited/deleted it right after submitting this ticket.

**Comment by diegoveloper** [comment]
I fixed your code; 

```dart
 body: FormKeyboardActions(
        config: KeyboardActionsConfig(
          actions: [
            KeyboardAction(
              focusNode: _focusNodeQuantity,
            ),
          ],
        ),
        child: Column(
          children: <Widget>[
            TextField(
              focusNode: _focusNodeQuantity,
              keyboardType: TextInputType.multiline,
              maxLines: null,
            ),
          ],
        ),
      ),
```

**Comment by AndroidGecko** [comment]
Thank you! 👍 
for some reason, I thought that the `FormKeyboardActions` widget has to be the direct parent of the `TextField`

**Comment by stevenspiel** [comment]
Is there no way to use KeyboardActions when wrapped in a Column?

```dart
import 'package:flutter/material.dart';
import 'package:keyboard_actions/keyboard_actions.dart';

class Foo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: <Widget>[
          KeyboardActions(
            config: KeyboardActionsConfig(
              keyboardActionsPlatform: KeyboardActionsPlatform.ALL,
              actions: [
                KeyboardAction(focusNode: FocusNode()),
              ],
            ),
            child: Text('foo'),
          ),
        ],
      ),
    );
  }
}
```

Running that raises the same error:

```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
BoxConstraints forces an infinite height.

These invalid constraints were provided to RenderParagraph's layout() function by the following function, which probably computed the invalid constraints in question:
  RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:264:13)
The offending constraints were: BoxConstraints(w=414.0, h=Infinity)
The relevant error-causing widget was: 
  KeyboardActions file:///Users/steven/mobile/example/lib/foo.dart:15:11
When the exception was thrown, this was the stack: 
#0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:517:9)
#1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:561:21)
#2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:565:6)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1668:24)
#4      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:264:13)
...
The following RenderObject was being processed when the exception was fired: RenderConstrainedBox#cc394 relayoutBoundary=up14 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
...  size: MISSING
...  additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=Infinity)
RenderObject: RenderConstrainedBox#cc394 relayoutBoundary=up14 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
  size: MISSING
  additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=Infinity)
...  child: RenderParagraph#08ca3 NEEDS-LAYOUT NEEDS-PAINT
...    parentData: <none>
...    constraints: MISSING
...    size: MISSING
...    textAlign: start
...    textDirection: ltr
...    softWrap: wrapping at box width
...    overflow: clip
...    locale: en_US
...    maxLines: unlimited
...    text: TextSpan
...      debugLabel: (englishLike body1 2014).merge(blackCupertino bodyText2)
...      inherit: false
...      color: Color(0xdd000000)
...      family: .SF UI Text
...      size: 14.0
...      weight: 400
...      baseline: alphabetic
...      decoration: TextDecoration.none
...      "foo"
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by rendering library ═════════════════════════════════════════════════
RenderBox was not laid out: RenderConstrainedBox#cc394 relayoutBoundary=up14 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
The relevant error-causing widget was: 
  KeyboardActions file:///Users/steven/mobile/example/foo.dart:15:11
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by diegoveloper** [comment]
Add KeyboardActions above Column

**Comment by stevenspiel** [comment]
@diegoveloper yeah, that certainly works. It just becomes really tough to handle all the focus nodes so high up in the widget tree, especially when child widgets are interchangeable. Is there any workaround?
