### ISSUE TITLE
what is footerBuilder error?

### ISSUE THREAD

**Issue by aimsugita** [diegoveloper/flutter_keyboard_actions#56]
```
════════ Exception caught by services library ══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during a platform message callback:
The getter 'footerBuilder' was called on null.
Receiver: null
Tried calling: footerBuilder

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      KeyboardActionstate._focusChanged (package:keyboard_actions/keyboard_actions.dart:219:26)
#2      KeyboardActionstate.didChangeAppLifecycleState (package:keyboard_actions/keyboard_actions.dart:373:9)
#3      WidgetsBinding.handleAppLifecycleStateChanged (package:flutter/src/widgets/binding.dart:536:16)
#4      SchedulerBinding._handleLifecycleMessage (package:flutter/src/scheduler/binding.dart:285:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by jmacpherson** [comment]
@diegoveloper Can we get a new version published to pub.dev? This issue is still live in the most recent release.

**Comment by diegoveloper** [comment]
hmm sure, just to confirm , could you use the  git repo url directly instead of the package version? just to be sure.

**Comment by jmacpherson** [comment]
@diegoveloper Yes, using direct from the repo resolves the issue.

**Comment by diegoveloper** [comment]
ok, I will upload a new version
